blank_issues_enabled: false
contact_links:
  - name: 調査用テンプレート
    url: https://github.com/zoudejun0319/firstTestForGithub/issues/new?template=調査用テンプレート.md
    about: Please ask and answer questions here.
  - name: 機能仕様書作成テンプレート
    url: https://github.com/zoudejun0319/firstTestForGithub/issues/new?template=機能仕様書作成テンプレート.md
    about: Please ask and answer questions here.

