blank_issues_enabled: false
contact_links:
  - name: GitHub Community Support
    url: https://github.com/zoudejun0319/firstTestForGithub/issues/new?template=feature_request (1).md
    about: Please ask and answer questions here.
