blank_issues_enabled false
contact_links
  - name GitHub Community Support
    url httpsgithub.comorgscommunitydiscussions
    about Please ask and answer questions here.
  - name GitHub Security Bug Bounty
    url httpsbounty.github.com
    about Please report security vulnerabilities here.
